<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../jacoco-resources/report.css" type="text/css"/><link rel="shortcut icon" href="../jacoco-resources/report.gif" type="image/gif"/><title>Functions.java</title><link rel="stylesheet" href="../jacoco-resources/prettify.css" type="text/css"/><script type="text/javascript" src="../jacoco-resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../jacoco-sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">Apache Commons Lang</a> &gt; <a href="index.source.html" class="el_package">org.apache.commons.lang3</a> &gt; <span class="el_source">Functions.java</span></div><h1>Functions.java</h1><pre class="source lang-java linenums">/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the &quot;License&quot;); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an &quot;AS IS&quot; BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.commons.lang3;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.lang.reflect.UndeclaredThrowableException;


/** This class provides utility functions, and classes for working with the
 * {@code java.util.function} package, or more generally, with Java 8
 * lambdas.
 * More specifically, it attempts to address the fact that lambdas are supposed
 * not to throw Exceptions, at least not checked Exceptions, aka instances of
 * {@link Exception}. This enforces the use of constructs like
 * &lt;pre&gt;
 *   Consumer&amp;lt;java.lang.reflect.Method&amp;gt; consumer = (m) -&amp;gt; {
 *       try {
 *           m.invoke(o, args);
 *       } catch (Throwable t) {
 *           throw Functions.rethrow(t);
 *       }
 *   };
 * &lt;/pre&gt;
 * By replacing a {@link java.util.function.Consumer Consumer&amp;lt;O&amp;gt;} with a
 * {@link FailableConsumer FailableConsumer&amp;lt;O,? extends Throwable&amp;gt;}, this can be
 * written like follows:
 * &lt;pre&gt;
 *   Functions.accept((m) -&amp;gt; m.invoke(o,args));
 * &lt;/pre&gt;
 * Obviously, the second version is much more concise and the spirit of
 * Lambda expressions is met better than the second version.
 */
<span class="nc" id="L48">public class Functions {</span>
    @FunctionalInterface
    public interface FailableRunnable&lt;T extends Throwable&gt; {
        /**
         * Runs the function.
         * @throws T if the function fails
         */
        void run() throws T;
    }
    @FunctionalInterface
    public interface FailableCallable&lt;O, T extends Throwable&gt; {
        /**
         * Calls the callable.
         * @return The value returned from the callable
         * @throws T if the callable fails
         */
        O call() throws T;
    }
    @FunctionalInterface
    public interface FailableConsumer&lt;O, T extends Throwable&gt; {
        /**
         * Accepts the consumer.
         * @param pObject the parameter for the consumable to accept
         * @throws T if the consumer fails
         */
        void accept(O pObject) throws T;
    }
    @FunctionalInterface
    public interface FailableBiConsumer&lt;O1, O2, T extends Throwable&gt; {
        /**
         * Accepts the consumer.
         * @param pObject1 the first parameter for the consumable to accept
         * @param pObject2 the second parameter for the consumable to accept
         * @throws T if the consumer fails
         */
        void accept(O1 pObject1, O2 pObject2) throws T;
    }
    @FunctionalInterface
    public interface FailableFunction&lt;I, O, T extends Throwable&gt; {
        /**
         * Apply the function.
         * @param pInput the input for the function
         * @return the result of the function
         * @throws T if the function fails
         */
        O apply(I pInput) throws T;
    }
    @FunctionalInterface
    public interface FailableBiFunction&lt;I1, I2, O, T extends Throwable&gt; {
        /**
         * Apply the function.
         * @param pInput1 the first input for the function
         * @param pInput2 the second input for the function
         * @return the result of the function
         * @throws T if the function fails
         */
        O apply(I1 pInput1, I2 pInput2) throws T;
    }
    @FunctionalInterface
    public interface FailablePredicate&lt;O, T extends Throwable&gt; {
        /**
         * Test the predicate.
         * @param pObject the object to test the predicate on
         * @return the predicate's evaluation
         * @throws T if the predicate fails
         */
        boolean test(O pObject) throws T;
    }
    @FunctionalInterface
    public interface FailableBiPredicate&lt;O1, O2, T extends Throwable&gt; {
        /**
         * Test the predicate.
         * @param pObject1 the first object to test the predicate on
         * @param pObject2 the second object to test the predicate on
         * @return the predicate's evaluation
         * @throws T if the predicate fails
         */
        boolean test(O1 pObject1, O2 pObject2) throws T;
    }

    /**
     * Runs a runnable and rethrows any exception as a {@link RuntimeException}.
     * @param pRunnable The runnable to run
     * @param &lt;T&gt; the type of checked exception the runnable may throw
     */
    public static &lt;T extends Throwable&gt; void run(FailableRunnable&lt;T&gt; pRunnable) {
        try {
<span class="fc" id="L135">            pRunnable.run();</span>
<span class="fc" id="L136">        } catch (Throwable t) {</span>
<span class="nc" id="L137">            throw rethrow(t);</span>
<span class="fc" id="L138">        }</span>
<span class="fc" id="L139">    }</span>

    /**
     * Calls a callable and rethrows any exception as a {@link RuntimeException}.
     * @param pCallable the callable to call
     * @param &lt;O&gt; the return type of the callable
     * @param &lt;T&gt; the type of checked exception the callable may throw
     * @return the value returned from the callable
     */
    public static &lt;O, T extends Throwable&gt; O call(FailableCallable&lt;O, T&gt; pCallable) {
        try {
<span class="fc" id="L150">            return pCallable.call();</span>
<span class="nc" id="L151">        } catch (Throwable t) {</span>
<span class="nc" id="L152">            throw rethrow(t);</span>
        }
    }

    /**
     * Consumes a consumer and rethrows any exception as a {@link RuntimeException}.
     * @param pConsumer the consumer to consume
     * @param pObject the object to consume by &lt;code&gt;pConsumer&lt;/code&gt;
     * @param &lt;O&gt; the type the consumer accepts
     * @param &lt;T&gt; the type of checked exception the consumer may throw
     */
    public static &lt;O, T extends Throwable&gt; void accept(FailableConsumer&lt;O, T&gt; pConsumer, O pObject) {
        try {
<span class="fc" id="L165">            pConsumer.accept(pObject);</span>
<span class="fc" id="L166">        } catch (Throwable t) {</span>
<span class="nc" id="L167">            throw rethrow(t);</span>
<span class="fc" id="L168">        }</span>
<span class="fc" id="L169">    }</span>

    /**
     * Consumes a consumer and rethrows any exception as a {@link RuntimeException}.
     * @param pConsumer the consumer to consume
     * @param pObject1 the first object to consume by &lt;code&gt;pConsumer&lt;/code&gt;
     * @param pObject2 the second object to consume by &lt;code&gt;pConsumer&lt;/code&gt;
     * @param &lt;O1&gt; the type of the first argument the consumer accepts
     * @param &lt;O2&gt; the type of the second argument the consumer accepts
     * @param &lt;T&gt; the type of checked exception the consumer may throw
     */
    public static &lt;O1, O2, T extends Throwable&gt; void accept(FailableBiConsumer&lt;O1, O2, T&gt; pConsumer, O1 pObject1, O2 pObject2) {
        try {
<span class="fc" id="L182">            pConsumer.accept(pObject1, pObject2);</span>
<span class="fc" id="L183">        } catch (Throwable t) {</span>
<span class="nc" id="L184">            throw rethrow(t);</span>
<span class="fc" id="L185">        }</span>
<span class="fc" id="L186">    }</span>

    /**
     * Applies a function and rethrows any exception as a {@link RuntimeException}.
     * @param pFunction the function to apply
     * @param pInput the input to apply &lt;code&gt;pFunction&lt;/code&gt; on
     * @param &lt;I&gt; the type of the argument the function accepts
     * @param &lt;O&gt; the return type of the function
     * @param &lt;T&gt; the type of checked exception the function may throw
     * @return the value returned from the function
     */
    public static &lt;I, O, T extends Throwable&gt; O apply(FailableFunction&lt;I, O, T&gt; pFunction, I pInput) {
        try {
<span class="fc" id="L199">            return pFunction.apply(pInput);</span>
<span class="fc" id="L200">        } catch (Throwable t) {</span>
<span class="nc" id="L201">            throw rethrow(t);</span>
        }
    }

    /**
     * Applies a function and rethrows any exception as a {@link RuntimeException}.
     * @param pFunction the function to apply
     * @param pInput1 the first input to apply &lt;code&gt;pFunction&lt;/code&gt; on
     * @param pInput2 the second input to apply &lt;code&gt;pFunction&lt;/code&gt; on
     * @param &lt;I1&gt; the type of the first argument the function accepts
     * @param &lt;I2&gt; the type of the second argument the function accepts
     * @param &lt;O&gt; the return type of the function
     * @param &lt;T&gt; the type of checked exception the function may throw
     * @return the value returned from the function
     */
    public static &lt;I1, I2, O, T extends Throwable&gt; O apply(FailableBiFunction&lt;I1, I2, O, T&gt; pFunction, I1 pInput1, I2 pInput2) {
        try {
<span class="fc" id="L218">            return pFunction.apply(pInput1, pInput2);</span>
<span class="fc" id="L219">        } catch (Throwable t) {</span>
<span class="nc" id="L220">            throw rethrow(t);</span>
        }
    }

    /**
     * Tests a predicate and rethrows any exception as a {@link RuntimeException}.
     * @param pPredicate the predicate to test
     * @param pObject the input to test by &lt;code&gt;pPredicate&lt;/code&gt;
     * @param &lt;O&gt; the type of argument the predicate tests
     * @param &lt;T&gt; the type of checked exception the predicate may throw
     * @return the boolean value returned by the predicate
     */
    public static &lt;O, T extends Throwable&gt; boolean test(FailablePredicate&lt;O, T&gt; pPredicate, O pObject) {
        try {
<span class="nc" id="L234">            return pPredicate.test(pObject);</span>
<span class="nc" id="L235">        } catch (Throwable t) {</span>
<span class="nc" id="L236">            throw rethrow(t);</span>
        }
    }

    /**
     * Tests a predicate and rethrows any exception as a {@link RuntimeException}.
     * @param pPredicate the predicate to test
     * @param pObject1 the first input to test by &lt;code&gt;pPredicate&lt;/code&gt;
     * @param pObject2 the second input to test by &lt;code&gt;pPredicate&lt;/code&gt;
     * @param &lt;O1&gt; the type of the first argument the predicate tests
     * @param &lt;O2&gt; the type of the second argument the predicate tests
     * @param &lt;T&gt; the type of checked exception the predicate may throw
     * @return the boolean value returned by the predicate
     */
    public static &lt;O1, O2, T extends Throwable&gt; boolean test(FailableBiPredicate&lt;O1, O2, T&gt; pPredicate, O1 pObject1, O2 pObject2) {
        try {
<span class="nc" id="L252">            return pPredicate.test(pObject1, pObject2);</span>
<span class="nc" id="L253">        } catch (Throwable t) {</span>
<span class="nc" id="L254">            throw rethrow(t);</span>
        }
    }

    /**
     * A simple try-with-resources implementation, that can be used, if your
     * objects do not implement the {@link AutoCloseable} interface. The method
     * executes the {@code pAction}. The method guarantees, that &lt;em&gt;all&lt;/em&gt;
     * the {@code pResources} are being executed, in the given order, afterwards,
     * and regardless of success, or failure. If either the original action, or
     * any of the resource action fails, then the &lt;em&gt;first&lt;/em&gt; failure (aka
     * {@link Throwable} is rethrown. Example use:
     * &lt;pre&gt;
     *   final FileInputStream fis = new FileInputStream(&quot;my.file&quot;);
     *   Functions.tryWithResources(useInputStream(fis), null, () -&amp;gt; fis.close());
     * &lt;/pre&gt;
     * @param pAction The action to execute. This object &lt;em&gt;will&lt;/em&gt; always
     *   be invoked.
     * @param pErrorHandler An optional error handler, which will be invoked finally,
     *   if any error occurred. The error handler will receive the first
     *   error, aka {@link Throwable}.
     * @param pResources The resource actions to execute. &lt;em&gt;All&lt;/em&gt; resource
     *   actions will be invoked, in the given order. A resource action is an
     *   instance of {@link FailableRunnable}, which will be executed.
     * @see #tryWithResources(FailableRunnable, FailableRunnable...)
     */
    @SafeVarargs
    public static void tryWithResources(FailableRunnable&lt;? extends Throwable&gt; pAction,
                                            FailableConsumer&lt;Throwable, ? extends Throwable&gt; pErrorHandler,
                                            FailableRunnable&lt;? extends Throwable&gt;... pResources) {
        final FailableConsumer&lt;Throwable, ? extends Throwable&gt; errorHandler;
<span class="pc bpc" id="L285" title="1 of 2 branches missed.">        if (pErrorHandler == null) {</span>
<span class="pc" id="L286">            errorHandler = (t) -&gt; rethrow(t);</span>
        } else {
<span class="nc" id="L288">            errorHandler = pErrorHandler;</span>
        }
<span class="pc bpc" id="L290" title="1 of 2 branches missed.">        if (pResources != null) {</span>
<span class="fc bfc" id="L291" title="All 2 branches covered.">            for (FailableRunnable&lt;? extends Throwable&gt; runnable : pResources) {</span>
<span class="pc bpc" id="L292" title="1 of 2 branches missed.">                if (runnable == null) {</span>
<span class="nc" id="L293">                    throw new NullPointerException(&quot;A resource action must not be null.&quot;);</span>
                }
            }
        }
<span class="fc" id="L297">        Throwable th = null;</span>
        try {
<span class="fc" id="L299">            pAction.run();</span>
<span class="fc" id="L300">        } catch (Throwable t) {</span>
<span class="fc" id="L301">            th = t;</span>
<span class="fc" id="L302">        }</span>
<span class="pc bpc" id="L303" title="1 of 2 branches missed.">        if (pResources != null) {</span>
<span class="fc bfc" id="L304" title="All 2 branches covered.">            for (FailableRunnable&lt;? extends Object&gt; runnable : pResources) {</span>
                try {
<span class="fc" id="L306">                    runnable.run();</span>
<span class="nc" id="L307">                } catch (Throwable t) {</span>
<span class="nc bnc" id="L308" title="All 2 branches missed.">                    if (th == null) {</span>
<span class="nc" id="L309">                        th = t;</span>
                    }
<span class="fc" id="L311">                }</span>
            }
        }
<span class="fc bfc" id="L314" title="All 2 branches covered.">        if (th != null) {</span>
            try {
<span class="nc" id="L316">                errorHandler.accept(th);</span>
<span class="fc" id="L317">            } catch (Throwable t) {</span>
<span class="nc" id="L318">                throw rethrow(t);</span>
<span class="nc" id="L319">            }</span>
        }
<span class="fc" id="L321">    }</span>

    /**
     * A simple try-with-resources implementation, that can be used, if your
     * objects do not implement the {@link AutoCloseable} interface. The method
     * executes the {@code pAction}. The method guarantees, that &lt;em&gt;all&lt;/em&gt;
     * the {@code pResources} are being executed, in the given order, afterwards,
     * and regardless of success, or failure. If either the original action, or
     * any of the resource action fails, then the &lt;em&gt;first&lt;/em&gt; failure (aka
     * {@link Throwable} is rethrown. Example use:
     * &lt;pre&gt;
     *   final FileInputStream fis = new FileInputStream(&quot;my.file&quot;);
     *   Functions.tryWithResources(useInputStream(fis), () -&amp;gt; fis.close());
     * &lt;/pre&gt;
     * @param pAction The action to execute. This object &lt;em&gt;will&lt;/em&gt; always
     *   be invoked.
     * @param pResources The resource actions to execute. &lt;em&gt;All&lt;/em&gt; resource
     *   actions will be invoked, in the given order. A resource action is an
     *   instance of {@link FailableRunnable}, which will be executed.
     * @see #tryWithResources(FailableRunnable, FailableConsumer, FailableRunnable...)
     */
    @SafeVarargs
    public static void tryWithResources(FailableRunnable&lt;? extends Throwable&gt; pAction,
                                            FailableRunnable&lt;? extends Throwable&gt;... pResources) {
<span class="fc" id="L345">        tryWithResources(pAction, null, pResources);</span>
<span class="fc" id="L346">    }</span>

    /**
     * Rethrow a {@link Throwable} as an unchecked exception.
     * @param pThrowable The throwable to rethrow
     * @return Never returns anything, this method never terminates normally
     */
    public static RuntimeException rethrow(Throwable pThrowable) {
<span class="pc bpc" id="L354" title="1 of 2 branches missed.">        if (pThrowable == null) {</span>
<span class="nc" id="L355">            throw new NullPointerException(&quot;The Throwable must not be null.&quot;);</span>
        } else {
<span class="fc bfc" id="L357" title="All 2 branches covered.">            if (pThrowable instanceof RuntimeException) {</span>
<span class="fc" id="L358">                throw (RuntimeException) pThrowable;</span>
<span class="fc bfc" id="L359" title="All 2 branches covered.">            } else if (pThrowable instanceof Error) {</span>
<span class="fc" id="L360">                throw (Error) pThrowable;</span>
<span class="fc bfc" id="L361" title="All 2 branches covered.">            } else if (pThrowable instanceof IOException) {</span>
<span class="fc" id="L362">                throw new UncheckedIOException((IOException) pThrowable);</span>
            } else {
<span class="fc" id="L364">                throw new UndeclaredThrowableException(pThrowable);</span>
            }
        }
    }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.jacoco.org/jacoco">JaCoCo</a> 0.8.5.201910111838</span></div></body></html>